name: Docker image build

on: push
    


jobs:
    build:

        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v4
            - name: Build & Push Image
              run: |
                echo ${{ secrets.DOCKERTOKEN }} | docker login -u "rishabhrawat167" --password-stdin
                docker build -t rishabhrawat167/devopslab8:v0.1 .
                docker push rishabhrawat167/devopslab8:v0.1